import puppeteer from 'puppeteer';
import { GeneratedPaper } from '../types';
import { IAssignment } from '../models/Assignment';

export class PDFService {
  async generatePDF(assignment: IAssignment): Promise<Buffer> {
    if (!assignment.generatedPaper) {
      throw new Error('No generated paper found');
    }

    const html = this.buildHTML(assignment);
    
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm'
      }
    });

    await browser.close();
    return pdf;
  }

  private buildHTML(assignment: IAssignment): string {
    const paper = assignment.generatedPaper!;
    
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Arial', sans-serif; padding: 20px; color: #333; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 15px; }
    .header h1 { font-size: 24px; margin-bottom: 10px; }
    .header .meta { font-size: 12px; color: #666; }
    .student-info { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin-bottom: 30px; padding: 15px; border: 1px solid #ddd; }
    .student-info .field { display: flex; flex-direction: column; }
    .student-info label { font-size: 11px; color: #666; margin-bottom: 5px; }
    .student-info .line { border-bottom: 1px solid #000; height: 25px; }
    .section { margin-bottom: 30px; }
    .section-header { background: #f5f5f5; padding: 10px 15px; margin-bottom: 15px; border-left: 4px solid #000; }
    .section-title { font-size: 16px; font-weight: bold; }
    .section-instruction { font-size: 12px; color: #666; margin-top: 5px; }
    .question { margin-bottom: 20px; padding-left: 10px; }
    .question-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
    .question-text { font-size: 14px; line-height: 1.6; }
    .question-meta { display: flex; gap: 10px; align-items: center; }
    .difficulty { padding: 3px 8px; border-radius: 3px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
    .difficulty.easy { background: #d4edda; color: #155724; }
    .difficulty.medium { background: #fff3cd; color: #856404; }
    .difficulty.hard { background: #f8d7da; color: #721c24; }
    .marks { font-size: 12px; font-weight: bold; color: #666; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #ddd; padding-top: 15px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${assignment.title}</h1>
    <div class="meta">
      <p>Total Marks: ${paper.totalMarks} | Total Questions: ${paper.totalQuestions}</p>
      <p>Due Date: ${new Date(assignment.dueDate).toLocaleDateString()}</p>
    </div>
  </div>

  <div class="student-info">
    <div class="field">
      <label>Name:</label>
      <div class="line"></div>
    </div>
    <div class="field">
      <label>Roll Number:</label>
      <div class="line"></div>
    </div>
    <div class="field">
      <label>Section:</label>
      <div class="line"></div>
    </div>
  </div>

  ${paper.sections.map((section, idx) => `
    <div class="section">
      <div class="section-header">
        <div class="section-title">${section.title}</div>
        <div class="section-instruction">${section.instruction}</div>
      </div>
      ${section.questions.map((q, qIdx) => `
        <div class="question">
          <div class="question-header">
            <div class="question-text"><strong>Q${qIdx + 1}.</strong> ${q.text}</div>
            <div class="question-meta">
              <span class="difficulty ${q.difficulty}">${q.difficulty}</span>
              <span class="marks">[${q.marks} marks]</span>
            </div>
          </div>
        </div>
      `).join('')}
    </div>
  `).join('')}

  <div class="footer">
    <p>Generated by VedaAI Assessment Creator</p>
  </div>
</body>
</html>`;
  }
}

export default new PDFService();
